# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonmm', '0002_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='deposit',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
