# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonmm', '0003_auto_20170211_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('t_amount', models.FloatField(default=0)),
                ('l_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('players', models.TextField()),
                ('place', models.CharField(max_length=64)),
                ('duration', models.IntegerField()),
                ('fee', models.FloatField()),
                ('ballused', models.IntegerField()),
                ('balltype', models.CharField(max_length=64)),
                ('aaprice', models.FloatField()),
            ],
        ),
    ]
