# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonmm', '0004_ball_membercount_playone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ball',
            name='l_count',
            field=models.IntegerField(default=0),
        ),
    ]
