# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonmm', '0005_ball_l_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='time',
            field=models.DateField(default=datetime.date(2017, 2, 12)),
        ),
    ]
