# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badmintonmm', '0006_auto_20170212_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='time',
            field=models.DateField(),
        ),
    ]
