# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDsClub', '0002_auto_20170404_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='play_time',
            field=models.CharField(default=2008, max_length=64),
            preserve_default=False,
        ),
    ]
