# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BDsClub', '0003_play_play_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=64)),
                ('wx_name', models.CharField(max_length=64)),
            ],
        ),
    ]
