# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 08:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='comment',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
