# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170111_0327'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogIndexPage',
            new_name='BlogHomePage',
        ),
    ]
