# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogdirpage_blogpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogHomePage',
            new_name='BlogIndexPage',
        ),
    ]
